name: Unit tests

on:
  push:
    branches:
      - main
      - snapshot
  pull_request:
    branches:
      - main
      - snapshot

jobs:
  pytest:
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout Overviewer
        uses: actions/checkout@v6

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y python3-dev python3-venv python3-pip build-essential git

      - name: Install dependencies
        run: |
          python3 -VV
          python3 -m venv .venv
          .venv/bin/python -m pip install --upgrade pip
          .venv/bin/python -m pip install -r requirements.txt
          .venv/bin/python -m pip install pytest pytest-mock
          PILLOW_VERSION=$(.venv/bin/python -c "import PIL; print(PIL.__version__)")
          git clone --branch="$PILLOW_VERSION" --depth=1 https://github.com/python-pillow/Pillow.git "$RUNNER_TEMP/pillow"
          echo "PIL_INCLUDE_DIR=$RUNNER_TEMP/pillow/src/libImaging" >> "$GITHUB_ENV"

      - name: Build Overviewer
        run: |
          .venv/bin/python setup.py build

      - name: Run tests with pytest
        run: |
          .venv/bin/python -m pytest
